### ISSUE TITLE
[IP] License File is missing

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/smartclide-security#2]
Dear @AnastasiosMargaritis 

There is any reason why this repo has no License file setup?
Thx

**Comment by phkrief** [comment]
Adding @deanone to expect an answer ;-)

**Comment by deanone** [comment]
Dear @phkrief I will check the license file. Mr. @AnastasiosMargaritis does not work for CERTH anymore, so I am asking you to remove him from the project.

 Best,

Athanasios
